 
 const constants = {
  ADD_COURSE: "ADD_COURSE",
  REMOVE_COURSE: "REMOVE_COURSE",
  ADD_ERROR: "ADD_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  ADD_ALERT: "ADD_ALERT",
  CLEAR_ALERT: "CLEAR_ALERT",
  CANCEL_FETCHING: "CANCEL_FETCHING",
  FETCH_COURSE: "FETCH_COURSE",
  CHANGE_COURSE_SUGGESTIONS: "CHANGE_COURSE_SUGGESTIONS",
  FETCH_SHUTTLE: "FETCH_SHUTTLE",
  CHANGE_SHUTTLE_LISTING: "CHANGE_SHUTTLE_LISTING",
  FETCH_CITIBIKE_STATION: "FETCH_CITIBIKE_STATION",
  FETCH_CITIBIKE_STATUS: "FETCH_CITIBIKE_STATUS",
  CHANGE_CITIBIKE_STATIONS: "CHANGE_CITIBIKE_STATIONS",
  CHANGE_CITIBIKE_LISTING: "CHANGE_CITIBIKE_LISTING",
  FETCH_SUBWAY: "FETCH_SUBWAY",
  CHANGE_SUBWAY_LISTING: "CHANGE_SUBWAY_LISTING",
  FETCH_MTABUS: "FETCH_MTABUS",
  CHANGE_MTABUS_LISTING: "CHANGE_MTABUS_LISTING",
  FETCH_DISTANCE: "FETCH_DISTANCE",
  
};
    
export default constants;