 
 const constants = {
  SET_NAME: "SET_NAME",
  SET_ARRIVAL_TIME: "SET_ARRIVAL_TIME",
  SET_USER_ADDRESS: "SET_USER_ADDRESS",
  ADD_COURSE: "ADD_COURSE",
  REMOVE_COURSE: "REMOVE_COURSE",
  ADD_ERROR: "ADD_ERROR",
  CLEAR_ERROR: "CLEAR_ERROR",
  ADD_ALERT: "ADD_ALERT",
  CLEAR_ALERT: "CLEAR_ALERT",
  ADD_FAVORITE_PLACE: "ADD_FAVORITE_PLACE",
  REMOVE_FAVORITE_PLACE: "REMOVE_FAVORITE_PLACE",

  CANCEL_FETCHING: "CANCEL_FETCHING",
  FETCH_COURSE: "FETCH_COURSE",
  CHANGE_COURSE_SUGGESTIONS: "CHANGE_COURSE_SUGGESTIONS",
  FETCH_SHUTTLE: "FETCH_SHUTTLE",
  CHANGE_SHUTTLE_LISTING: "CHANGE_SHUTTLE_LISTING",
  FETCH_PASSIO_DIRECTIONS: "FETCH_PASSIO_DIRECTIONS",
  LOAD_PASSIO_DIRECTIONS: "LOAD_PASSIO_DIRECTIONS",
  FETCH_GOOGLE_DIRECTIONS: "FETCH_GOOGLE_DIRECTIONS",
  LOAD_GOOGLE_DIRECTIONS: "LOAD_GOOGLE_DIRECTIONS",

  

  /*FETCH_CITIBIKE_STATION: "FETCH_CITIBIKE_STATION",
  FETCH_CITIBIKE_STATUS: "FETCH_CITIBIKE_STATUS",
  CHANGE_CITIBIKE_STATIONS: "CHANGE_CITIBIKE_STATIONS",
  CHANGE_CITIBIKE_LISTING: "CHANGE_CITIBIKE_LISTING",
  */
 
  // FETCH_ALL_DATA: "FETCH_ALL_DATA",
  // CHANGE_DATA_LISTINGS: "CHANGE_DATA_LISTINGS"
  
};
    
export default constants;